site_name: Upper level ontology for smart city indicators
site_description: This ontology enables the representation of smart city indicator
  definitions and the data used to derive them..
repo_url: https://github.com/ISO-TC204/ontology-i72-v1
nav:
- Home: index.md
- i72:
  - i72: i72.md
  - Application_area: Application_area.md
  - Binary_prefix: Binary_prefix.md
  - Cardinal_scale: Cardinal_scale.md
  - Cardinality: Cardinality.md
  - Cardinality_scale: Cardinality_scale.md
  - Cardinality_unit: Cardinality_unit.md
  - City: City.md
  - Compound_unit: Compound_unit.md
  - Difference Indicator: DifferenceIndicator.md
  - Dimension: Dimension.md
  - Distinct_count: Distinct_count.md
  - Feature: Feature.md
  - Fixed_point: Fixed_point.md
  - Fixed_zero_point: Fixed_zero_point.md
  - Indicator: Indicator.md
  - Interval_scale: Interval_scale.md
  - Mean: Mean.md
  - Measure: Measure.md
  - Measurement_scale: Measurement_scale.md
  - Measurement_scale_category: Measurement_scale_category.md
  - Monetary_unit: Monetary_unit.md
  - Nominal_scale: Nominal_scale.md
  - Observation: Observation.md
  - Ordered_measurement_scale_category: Ordered_measurement_scale_category.md
  - Ordinal_scale: Ordinal_scale.md
  - Parameter: Parameter.md
  - Phenomenon: Phenomenon.md
  - Point: Point.md
  - Population: Population.md
  - Prefix: Prefix.md
  - Quantity: Quantity.md
  - Ratio_scale: Ratio_scale.md
  - Ratio Indicator: RatioIndicator.md
  - Sample: Sample.md
  - Sample_cardinality: Sample_cardinality.md
  - Sample_mean: Sample_mean.md
  - Sample_standard_deviation: Sample_standard_deviation.md
  - Sample_sum: Sample_sum.md
  - SI_prefix: SI_prefix.md
  - Singular_unit: Singular_unit.md
  - Standard_deviation: Standard_deviation.md
  - Statistic: Statistic.md
  - Sum: Sum.md
  - Sum Indicator: SumIndicator.md
  - System_of_units: System_of_units.md
  - Unit_division: Unit_division.md
  - Unit_exponentiation: Unit_exponentiation.md
  - Unit_multiple_or_submultiple: Unit_multiple_or_submultiple.md
  - Unit_multiplication: Unit_multiplication.md
  - Unit_of_measure: Unit_of_measure.md
  - Variable: Variable.md
  - Vectorial_or_tensorial_character: Vectorial_or_tensorial_character.md
site_url: https://isotc204.org/ontology-i72-v1
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
